# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import project.game.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('board', models.CharField(default=b'.........', max_length=9)),
                ('turns', models.IntegerField(default=5)),
                ('position', models.CharField(default=project.game.models.get_initial_position, max_length=2)),
                ('state', models.CharField(default=b'p', max_length=1)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
